import { mutation } from "./_generated/server";
import { Id } from "./_generated/dataModel";

export const insertSizes = mutation(async (ctx) => {
  // Fetch all products from the database
  const products = await ctx.db.query("products").collect();

  // Create a map of product details to their IDs
  const productMap = products.reduce((map, product) => {
    const productKey = `${product.brand}-${product.Series}-${product.productName}`.trim();
    map[productKey] = product._id;
    return map;
  }, {} as Record<string, Id<"products">>);

  const sizes = [
    // Sizes for ProductID 13 (Power Cushion 65Z 3)
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65Z 3", sizeRegion: "UK", sizeValue: "12.50" },

    //Raw ProductID 14
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "22" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "4" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "3.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "22.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "4.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "4" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "23" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "4.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "23.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "24" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "24.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "25" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "25.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "26" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 65X 3", sizeRegion: "UK", sizeValue: "12.50" },

    // Sizes for ProductID 15 (Power Cushion Comfort Z 3)
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion Comfort Z 3", sizeRegion: "UK", sizeValue: "12.50" },

    // Sizes for ProductID 16 (Power Cushion 88 DIAL 3)
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "22" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "4" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "3.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "22.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "4.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "4" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "23" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "4.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "23.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "24" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "24.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "25" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "25.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "26" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion 88 DIAL 3", sizeRegion: "UK", sizeValue: "12.50" },
    // Sizes for ProductID 17 (Power Cushion SHB65XLEX)
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "22" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "4" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "3.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "22.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "4.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "4" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "23" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "4.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "23.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "24" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "24.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "5.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "25" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "6" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "25.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "6.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "26" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "7" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Yonex", series: "-", productName: "Power Cushion SHB65XLEX", sizeRegion: "UK", sizeValue: "12.50" },
    // Sizes for ProductID 18 (Anti-Slippery K-530)
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "22" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "4" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "5.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "3.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "22.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "4.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "6" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "4" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "23" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "5" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "6.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "4.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "23.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "5.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "24" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "24.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "7.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "5.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "25" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "6.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "8" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "6" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "25.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "7" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "8.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "6.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "26" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "7.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "9" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "7" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Kawasaki", series: "-", productName: "Anti-Slippery K-530", sizeRegion: "UK", sizeValue: "12.50" },


    // Sizes for ProductID 19 (Ultra 2)
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Li-Ning", series: "-", productName: "Ultra 2", sizeRegion: "UK", sizeValue: "12.50" },
    // Sizes for ProductID 20 (AYTS034-6)
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "22" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "4" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "5.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "3.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "22.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "4.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "6" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "4" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "23" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "5" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "6.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "4.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "23.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "5.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "24" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "24.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "7.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "5.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "25" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "6.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "8" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "6" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "25.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "7" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "8.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "6.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "26" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "7.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "9" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "7" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Li-Ning", series: "-", productName: "AYTS034-6", sizeRegion: "UK", sizeValue: "12.50" },
    // Sizes for ProductID 21 (X Crayon ShinChan A39CS)
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "22" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "4" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "5.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "3.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "22.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "4.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "6" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "4" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "23" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "5" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "6.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "4.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "23.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "5.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "24" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "7" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "5" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "24.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "6" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "7.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "5.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "25" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "6.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "8" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "6" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "25.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "7" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "8.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "6.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "26" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "7.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "9" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "7" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Victor", series: "-", productName: "X Crayon ShinChan A39CS", sizeRegion: "UK", sizeValue: "12.50" },
    // Sizes for ProductID 22 (A970 Nitro Lite)
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "26.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "8" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "9.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "7.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "27" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "8.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "10" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "8" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "27.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "9" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "10.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "8.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "28" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "9.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "11" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "9" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "28.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "10" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "11.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "9.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "29" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "10.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "12" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "10" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "29.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "11" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "12.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "10.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "30" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "11.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "13" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "11" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "30.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "12" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "13.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "11.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "cm", sizeValue: "31" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Men)", sizeValue: "13" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "US(Women)", sizeValue: "14.50" },
    { brand: "Victor", series: "-", productName: "A970 Nitro Lite", sizeRegion: "UK", sizeValue: "12.50" },
]
  for (const { brand, series, productName, sizeRegion, sizeValue } of sizes) {
    const productKey = `${brand}-${series}-${productName}`.trim();
    const productId = productMap[productKey];

    if (!productId) {
      console.log(`Product "${brand} ${series} ${productName}" not found. Skipping size insertion.`);
      continue;
    }

    // Insert size entry into the size table
    await ctx.db.insert("size", {
      productID: productId,
      SizeRegion: sizeRegion,
      SizeValue: sizeValue,
    });

    console.log(`Inserted size for product "${productName}" with region: ${sizeRegion}, value: ${sizeValue}`);
  }
});
