import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "../../Providers/convex-client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ConvexClientProvider>
          <nav>
            <a href="/"></a>
            <a href="/Brands"></a>
            <a href="/ContactUs"></a>
            <a href="/AboutUs"></a>
            <a href="/Accessories"></a>
            <a href="/AccessoriesDetail"></a>
          </nav>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}